







#define CONFIG_TOOLPREFIX "xtensa-esp32-elf-"
#define CONFIG_PYTHON "python"
#define CONFIG_MAKE_WARN_UNDEFINED_VARIABLES 1




#define CONFIG_LOG_BOOTLOADER_LEVEL_NONE 0
#define CONFIG_LOG_BOOTLOADER_LEVEL_ERROR 0
#define CONFIG_LOG_BOOTLOADER_LEVEL_WARN 0
#define CONFIG_LOG_BOOTLOADER_LEVEL_INFO 0
#define CONFIG_LOG_BOOTLOADER_LEVEL_DEBUG 1
#define CONFIG_LOG_BOOTLOADER_LEVEL_VERBOSE 0
#define CONFIG_LOG_BOOTLOADER_LEVEL 4
#define CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V 1
#define CONFIG_BOOTLOADER_FACTORY_RESET 0
#define CONFIG_BOOTLOADER_APP_TEST 0




#define CONFIG_SECURE_BOOT_ENABLED 0
#define CONFIG_FLASH_ENCRYPTION_ENABLED 0




#define CONFIG_ESPTOOLPY_PORT "/dev/ttyUSB0"
#define CONFIG_ESPTOOLPY_BAUD_115200B
#define CONFIG_ESPTOOLPY_BAUD_230400B
#define CONFIG_ESPTOOLPY_BAUD_921600B 1
#define CONFIG_ESPTOOLPY_BAUD_2MB
#define CONFIG_ESPTOOLPY_BAUD_OTHER 0
#define CONFIG_ESPTOOLPY_BAUD_OTHER_VAL 115200
#define CONFIG_ESPTOOLPY_BAUD 921600
#define CONFIG_ESPTOOLPY_COMPRESSED 1
#define CONFIG_FLASHMODE_QIO 0
#define CONFIG_FLASHMODE_QOUT 0
#define CONFIG_FLASHMODE_DIO 1
#define CONFIG_FLASHMODE_DOUT 0
#define CONFIG_ESPTOOLPY_FLASHMODE "dio"
#define CONFIG_ESPTOOLPY_FLASHFREQ_80M 1
#define CONFIG_ESPTOOLPY_FLASHFREQ_40M
#define CONFIG_ESPTOOLPY_FLASHFREQ_26M
#define CONFIG_ESPTOOLPY_FLASHFREQ_20M
#define CONFIG_ESPTOOLPY_FLASHFREQ "80m"
#define CONFIG_ESPTOOLPY_FLASHSIZE_1MB
#define CONFIG_ESPTOOLPY_FLASHSIZE_2MB
#define CONFIG_ESPTOOLPY_FLASHSIZE_4MB 1
#define CONFIG_ESPTOOLPY_FLASHSIZE_8MB
#define CONFIG_ESPTOOLPY_FLASHSIZE_16MB
#define CONFIG_ESPTOOLPY_FLASHSIZE "4MB"
#define CONFIG_ESPTOOLPY_FLASHSIZE_DETECT 1
#define CONFIG_ESPTOOLPY_BEFORE_RESET 1
#define CONFIG_ESPTOOLPY_BEFORE_NORESET 0
#define CONFIG_ESPTOOLPY_BEFORE "default_reset"
#define CONFIG_ESPTOOLPY_AFTER_RESET 1
#define CONFIG_ESPTOOLPY_AFTER_NORESET 0
#define CONFIG_ESPTOOLPY_AFTER "hard_reset"
#define CONFIG_MONITOR_BAUD_9600B
#define CONFIG_MONITOR_BAUD_57600B
#define CONFIG_MONITOR_BAUD_115200B 1
#define CONFIG_MONITOR_BAUD_230400B
#define CONFIG_MONITOR_BAUD_921600B
#define CONFIG_MONITOR_BAUD_2MB
#define CONFIG_MONITOR_BAUD_OTHER 0
#define CONFIG_MONITOR_BAUD_OTHER_VAL 115200
#define CONFIG_MONITOR_BAUD 115200




#define CONFIG_FATFS_BASE_ADDR 0x210000
#define CONFIG_FATFS_SIZE 1048576




#define CONFIG_PARTITION_TABLE_SINGLE_APP 0
#define CONFIG_PARTITION_TABLE_TWO_OTA 0
#define CONFIG_PARTITION_TABLE_CUSTOM 1
#define CONFIG_PARTITION_TABLE_CUSTOM_FILENAME "partitions.csv"
#define CONFIG_PARTITION_TABLE_FILENAME "partitions.csv"
#define CONFIG_PARTITION_TABLE_OFFSET 0x8000
#define CONFIG_PARTITION_TABLE_MD5 1




#define CONFIG_OPTIMIZATION_LEVEL_DEBUG 0
#define CONFIG_OPTIMIZATION_LEVEL_RELEASE 1
#define CONFIG_OPTIMIZATION_ASSERTIONS_ENABLED 1
#define CONFIG_OPTIMIZATION_ASSERTIONS_SILENT 0
#define CONFIG_OPTIMIZATION_ASSERTIONS_DISABLED 0
#define CONFIG_CXX_EXCEPTIONS_EMG_POOL_SIZE 0
#define CONFIG_STACK_CHECK_NONE 1
#define CONFIG_STACK_CHECK_NORM 0
#define CONFIG_STACK_CHECK_STRONG 0
#define CONFIG_STACK_CHECK_ALL 0
#define CONFIG_STACK_CHECK 0
#define CONFIG_WARN_WRITE_STRINGS 0








#define CONFIG_ESP32_APPTRACE_DEST_TRAX
#define CONFIG_ESP32_APPTRACE_DEST_NONE 1
#define CONFIG_ESP32_APPTRACE_ENABLE
#define CONFIG_ESP32_APPTRACE_LOCK_ENABLE 1
#define CONFIG_AWS_IOT_SDK 0




#define CONFIG_BT_ENABLED 1
#define CONFIG_BTDM_CONTROLLER_PINNED_TO_CORE_0 1
#define CONFIG_BTDM_CONTROLLER_PINNED_TO_CORE_1
#define CONFIG_BTDM_CONTROLLER_PINNED_TO_CORE 0
#define CONFIG_BTDM_CONTROLLER_HCI_MODE_VHCI 1
#define CONFIG_BTDM_CONTROLLER_HCI_MODE_UART_H4




#define CONFIG_BTDM_CONTROLLER_MODEM_SLEEP 0
#define CONFIG_BLUEDROID_ENABLED 1
#define CONFIG_BLUEDROID_PINNED_TO_CORE_0 1
#define CONFIG_BLUEDROID_PINNED_TO_CORE_1
#define CONFIG_BLUEDROID_PINNED_TO_CORE 0
#define CONFIG_BTC_TASK_STACK_SIZE 8000
#define CONFIG_BLUEDROID_MEM_DEBUG 0
#define CONFIG_CLASSIC_BT_ENABLED 0
#define CONFIG_GATTS_ENABLE 1
#define CONFIG_GATTC_ENABLE 1
#define CONFIG_GATTC_CACHE_NVS_FLASH 0
#define CONFIG_BLE_SMP_ENABLE 1
#define CONFIG_BT_STACK_NO_LOG 0




#define CONFIG_HCI_TRACE_LEVEL_NONE 0
#define CONFIG_HCI_TRACE_LEVEL_ERROR 0
#define CONFIG_HCI_TRACE_LEVEL_WARNING 1
#define CONFIG_HCI_TRACE_LEVEL_API 0
#define CONFIG_HCI_TRACE_LEVEL_EVENT 0
#define CONFIG_HCI_TRACE_LEVEL_DEBUG 0
#define CONFIG_HCI_TRACE_LEVEL_VERBOSE 0
#define CONFIG_HCI_INITIAL_TRACE_LEVEL 2
#define CONFIG_BTM_TRACE_LEVEL_NONE 0
#define CONFIG_BTM_TRACE_LEVEL_ERROR 0
#define CONFIG_BTM_TRACE_LEVEL_WARNING 1
#define CONFIG_BTM_TRACE_LEVEL_API 0
#define CONFIG_BTM_TRACE_LEVEL_EVENT 0
#define CONFIG_BTM_TRACE_LEVEL_DEBUG 0
#define CONFIG_BTM_TRACE_LEVEL_VERBOSE 0
#define CONFIG_BTM_INITIAL_TRACE_LEVEL 2
#define CONFIG_L2CAP_TRACE_LEVEL_NONE
#define CONFIG_L2CAP_TRACE_LEVEL_ERROR
#define CONFIG_L2CAP_TRACE_LEVEL_WARNING 1
#define CONFIG_L2CAP_TRACE_LEVEL_API
#define CONFIG_L2CAP_TRACE_LEVEL_EVENT
#define CONFIG_L2CAP_TRACE_LEVEL_DEBUG
#define CONFIG_L2CAP_TRACE_LEVEL_VERBOSE
#define CONFIG_L2CAP_INITIAL_TRACE_LEVEL 2
#define CONFIG_RFCOMM_TRACE_LEVEL_NONE 0
#define CONFIG_RFCOMM_TRACE_LEVEL_ERROR 0
#define CONFIG_RFCOMM_TRACE_LEVEL_WARNING 1
#define CONFIG_RFCOMM_TRACE_LEVEL_API 0
#define CONFIG_RFCOMM_TRACE_LEVEL_EVENT 0
#define CONFIG_RFCOMM_TRACE_LEVEL_DEBUG 0
#define CONFIG_RFCOMM_TRACE_LEVEL_VERBOSE 0
#define CONFIG_RFCOMM_INITIAL_TRACE_LEVEL 2
#define CONFIG_SDP_TRACE_LEVEL_NONE 0
#define CONFIG_SDP_TRACE_LEVEL_ERROR 0
#define CONFIG_SDP_TRACE_LEVEL_WARNING 1
#define CONFIG_SDP_TRACE_LEVEL_API 0
#define CONFIG_SDP_TRACE_LEVEL_EVENT 0
#define CONFIG_SDP_TRACE_LEVEL_DEBUG 0
#define CONFIG_SDP_TRACE_LEVEL_VERBOSE 0
#define CONFIG_SDP_INITIAL_TRACE_LEVEL 2
#define CONFIG_GAP_TRACE_LEVEL_NONE 0
#define CONFIG_GAP_TRACE_LEVEL_ERROR 0
#define CONFIG_GAP_TRACE_LEVEL_WARNING 1
#define CONFIG_GAP_TRACE_LEVEL_API 0
#define CONFIG_GAP_TRACE_LEVEL_EVENT 0
#define CONFIG_GAP_TRACE_LEVEL_DEBUG 0
#define CONFIG_GAP_TRACE_LEVEL_VERBOSE 0
#define CONFIG_GAP_INITIAL_TRACE_LEVEL 2
#define CONFIG_BNEP_TRACE_LEVEL_NONE 0
#define CONFIG_BNEP_TRACE_LEVEL_ERROR 0
#define CONFIG_BNEP_TRACE_LEVEL_WARNING 1
#define CONFIG_BNEP_TRACE_LEVEL_API 0
#define CONFIG_BNEP_TRACE_LEVEL_EVENT 0
#define CONFIG_BNEP_TRACE_LEVEL_DEBUG 0
#define CONFIG_BNEP_TRACE_LEVEL_VERBOSE 0
#define CONFIG_BNEP_INITIAL_TRACE_LEVEL 2
#define CONFIG_PAN_TRACE_LEVEL_NONE 0
#define CONFIG_PAN_TRACE_LEVEL_ERROR 0
#define CONFIG_PAN_TRACE_LEVEL_WARNING 1
#define CONFIG_PAN_TRACE_LEVEL_API 0
#define CONFIG_PAN_TRACE_LEVEL_EVENT 0
#define CONFIG_PAN_TRACE_LEVEL_DEBUG 0
#define CONFIG_PAN_TRACE_LEVEL_VERBOSE 0
#define CONFIG_PAN_INITIAL_TRACE_LEVEL 2
#define CONFIG_A2D_TRACE_LEVEL_NONE
#define CONFIG_A2D_TRACE_LEVEL_ERROR
#define CONFIG_A2D_TRACE_LEVEL_WARNING 1
#define CONFIG_A2D_TRACE_LEVEL_API
#define CONFIG_A2D_TRACE_LEVEL_EVENT
#define CONFIG_A2D_TRACE_LEVEL_DEBUG
#define CONFIG_A2D_TRACE_LEVEL_VERBOSE
#define CONFIG_A2D_INITIAL_TRACE_LEVEL 2
#define CONFIG_AVDT_TRACE_LEVEL_NONE 0
#define CONFIG_AVDT_TRACE_LEVEL_ERROR 0
#define CONFIG_AVDT_TRACE_LEVEL_WARNING 1
#define CONFIG_AVDT_TRACE_LEVEL_API 0
#define CONFIG_AVDT_TRACE_LEVEL_EVENT 0
#define CONFIG_AVDT_TRACE_LEVEL_DEBUG 0
#define CONFIG_AVDT_TRACE_LEVEL_VERBOSE 0
#define CONFIG_AVDT_INITIAL_TRACE_LEVEL 2
#define CONFIG_AVCT_TRACE_LEVEL_NONE 0
#define CONFIG_AVCT_TRACE_LEVEL_ERROR 0
#define CONFIG_AVCT_TRACE_LEVEL_WARNING 1
#define CONFIG_AVCT_TRACE_LEVEL_API 0
#define CONFIG_AVCT_TRACE_LEVEL_EVENT 0
#define CONFIG_AVCT_TRACE_LEVEL_DEBUG 0
#define CONFIG_AVCT_TRACE_LEVEL_VERBOSE 0
#define CONFIG_AVCT_INITIAL_TRACE_LEVEL 2
#define CONFIG_AVRC_TRACE_LEVEL_NONE 0
#define CONFIG_AVRC_TRACE_LEVEL_ERROR 0
#define CONFIG_AVRC_TRACE_LEVEL_WARNING 1
#define CONFIG_AVRC_TRACE_LEVEL_API 0
#define CONFIG_AVRC_TRACE_LEVEL_EVENT 0
#define CONFIG_AVRC_TRACE_LEVEL_DEBUG 0
#define CONFIG_AVRC_TRACE_LEVEL_VERBOSE 0
#define CONFIG_AVRC_INITIAL_TRACE_LEVEL 2
#define CONFIG_MCA_TRACE_LEVEL_NONE 0
#define CONFIG_MCA_TRACE_LEVEL_ERROR 0
#define CONFIG_MCA_TRACE_LEVEL_WARNING 1
#define CONFIG_MCA_TRACE_LEVEL_API 0
#define CONFIG_MCA_TRACE_LEVEL_EVENT 0
#define CONFIG_MCA_TRACE_LEVEL_DEBUG 0
#define CONFIG_MCA_TRACE_LEVEL_VERBOSE 0
#define CONFIG_MCA_INITIAL_TRACE_LEVEL 2
#define CONFIG_HID_TRACE_LEVEL_NONE 0
#define CONFIG_HID_TRACE_LEVEL_ERROR 0
#define CONFIG_HID_TRACE_LEVEL_WARNING 1
#define CONFIG_HID_TRACE_LEVEL_API 0
#define CONFIG_HID_TRACE_LEVEL_EVENT 0
#define CONFIG_HID_TRACE_LEVEL_DEBUG 0
#define CONFIG_HID_TRACE_LEVEL_VERBOSE 0
#define CONFIG_HID_INITIAL_TRACE_LEVEL 2
#define CONFIG_APPL_TRACE_LEVEL_NONE 0
#define CONFIG_APPL_TRACE_LEVEL_ERROR 0
#define CONFIG_APPL_TRACE_LEVEL_WARNING 1
#define CONFIG_APPL_TRACE_LEVEL_API 0
#define CONFIG_APPL_TRACE_LEVEL_EVENT 0
#define CONFIG_APPL_TRACE_LEVEL_DEBUG 0
#define CONFIG_APPL_TRACE_LEVEL_VERBOSE 0
#define CONFIG_APPL_INITIAL_TRACE_LEVEL 2
#define CONFIG_GATT_TRACE_LEVEL_NONE 0
#define CONFIG_GATT_TRACE_LEVEL_ERROR 0
#define CONFIG_GATT_TRACE_LEVEL_WARNING 1
#define CONFIG_GATT_TRACE_LEVEL_API 0
#define CONFIG_GATT_TRACE_LEVEL_EVENT 0
#define CONFIG_GATT_TRACE_LEVEL_DEBUG 0
#define CONFIG_GATT_TRACE_LEVEL_VERBOSE 0
#define CONFIG_GATT_INITIAL_TRACE_LEVEL 2
#define CONFIG_SMP_TRACE_LEVEL_NONE 0
#define CONFIG_SMP_TRACE_LEVEL_ERROR 0
#define CONFIG_SMP_TRACE_LEVEL_WARNING 1
#define CONFIG_SMP_TRACE_LEVEL_API 0
#define CONFIG_SMP_TRACE_LEVEL_EVENT 0
#define CONFIG_SMP_TRACE_LEVEL_DEBUG 0
#define CONFIG_SMP_TRACE_LEVEL_VERBOSE 0
#define CONFIG_SMP_INITIAL_TRACE_LEVEL 2
#define CONFIG_BTIF_TRACE_LEVEL_NONE 0
#define CONFIG_BTIF_TRACE_LEVEL_ERROR 0
#define CONFIG_BTIF_TRACE_LEVEL_WARNING 1
#define CONFIG_BTIF_TRACE_LEVEL_API 0
#define CONFIG_BTIF_TRACE_LEVEL_EVENT 0
#define CONFIG_BTIF_TRACE_LEVEL_DEBUG 0
#define CONFIG_BTIF_TRACE_LEVEL_VERBOSE 0
#define CONFIG_BTIF_INITIAL_TRACE_LEVEL 2
#define CONFIG_BTC_TRACE_LEVEL_NONE 0
#define CONFIG_BTC_TRACE_LEVEL_ERROR 0
#define CONFIG_BTC_TRACE_LEVEL_WARNING 1
#define CONFIG_BTC_TRACE_LEVEL_API 0
#define CONFIG_BTC_TRACE_LEVEL_EVENT 0
#define CONFIG_BTC_TRACE_LEVEL_DEBUG 0
#define CONFIG_BTC_TRACE_LEVEL_VERBOSE 0
#define CONFIG_BTC_INITIAL_TRACE_LEVEL 2
#define CONFIG_OSI_TRACE_LEVEL_NONE 0
#define CONFIG_OSI_TRACE_LEVEL_ERROR 0
#define CONFIG_OSI_TRACE_LEVEL_WARNING 1
#define CONFIG_OSI_TRACE_LEVEL_API 0
#define CONFIG_OSI_TRACE_LEVEL_EVENT 0
#define CONFIG_OSI_TRACE_LEVEL_DEBUG 0
#define CONFIG_OSI_TRACE_LEVEL_VERBOSE 0
#define CONFIG_OSI_INITIAL_TRACE_LEVEL 2
#define CONFIG_BLUFI_TRACE_LEVEL_NONE 0
#define CONFIG_BLUFI_TRACE_LEVEL_ERROR 0
#define CONFIG_BLUFI_TRACE_LEVEL_WARNING 1
#define CONFIG_BLUFI_TRACE_LEVEL_API 0
#define CONFIG_BLUFI_TRACE_LEVEL_EVENT 0
#define CONFIG_BLUFI_TRACE_LEVEL_DEBUG 0
#define CONFIG_BLUFI_TRACE_LEVEL_VERBOSE 0
#define CONFIG_BLUFI_INITIAL_TRACE_LEVEL 2
#define CONFIG_BT_ACL_CONNECTIONS 4
#define CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST 0
#define CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY 0
#define CONFIG_BLE_HOST_QUEUE_CONGESTION_CHECK 0
#define CONFIG_BLE_SCAN_DUPLICATE 1
#define CONFIG_DUPLICATE_SCAN_CACHE_SIZE 50
#define CONFIG_BLE_MESH_SCAN_DUPLICATE_EN 0
#define CONFIG_SMP_ENABLE 1
#define CONFIG_BT_RESERVE_DRAM 0x10000








#define CONFIG_ADC_FORCE_XPD_FSM 0
#define CONFIG_ADC2_DISABLE_DAC 1




#define CONFIG_SPI_MASTER_IN_IRAM 0
#define CONFIG_SPI_MASTER_ISR_IN_IRAM 1




#define CONFIG_ESP32_DEFAULT_CPU_FREQ_80
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_160 1
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_240
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ 160
#define CONFIG_SPIRAM_SUPPORT 0
#define CONFIG_MEMMAP_TRACEMEM 0
#define CONFIG_MEMMAP_TRACEMEM_TWOBANKS 0
#define CONFIG_ESP32_TRAX
#define CONFIG_TRACEMEM_RESERVE_DRAM 0x0
#define CONFIG_ESP32_ENABLE_COREDUMP_TO_FLASH
#define CONFIG_ESP32_ENABLE_COREDUMP_TO_UART 1
#define CONFIG_ESP32_ENABLE_COREDUMP_TO_NONE
#define CONFIG_ESP32_ENABLE_COREDUMP 1
#define CONFIG_ESP32_CORE_DUMP_UART_DELAY 0
#define CONFIG_ESP32_CORE_DUMP_LOG_LEVEL 1
#define CONFIG_TWO_UNIVERSAL_MAC_ADDRESS 0
#define CONFIG_FOUR_UNIVERSAL_MAC_ADDRESS 1
#define CONFIG_NUMBER_OF_UNIVERSAL_MAC_ADDRESS 4
#define CONFIG_SYSTEM_EVENT_QUEUE_SIZE 32
#define CONFIG_SYSTEM_EVENT_TASK_STACK_SIZE 2048
#define CONFIG_MAIN_TASK_STACK_SIZE 3584
#define CONFIG_IPC_TASK_STACK_SIZE 1024
#define CONFIG_TIMER_TASK_STACK_SIZE 3584
#define CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF 1
#define CONFIG_NEWLIB_STDOUT_LINE_ENDING_LF 0
#define CONFIG_NEWLIB_STDOUT_LINE_ENDING_CR 0
#define CONFIG_NEWLIB_STDIN_LINE_ENDING_CRLF 0
#define CONFIG_NEWLIB_STDIN_LINE_ENDING_LF 0
#define CONFIG_NEWLIB_STDIN_LINE_ENDING_CR 1
#define CONFIG_NEWLIB_NANO_FORMAT 0
#define CONFIG_CONSOLE_UART_DEFAULT 1
#define CONFIG_CONSOLE_UART_CUSTOM 0
#define CONFIG_CONSOLE_UART_NONE 0
#define CONFIG_CONSOLE_UART_NUM 0
#define CONFIG_CONSOLE_UART_BAUDRATE 115200
#define CONFIG_ULP_COPROC_ENABLED 0
#define CONFIG_ULP_COPROC_RESERVE_MEM 0
#define CONFIG_ESP32_PANIC_PRINT_HALT
#define CONFIG_ESP32_PANIC_PRINT_REBOOT 1
#define CONFIG_ESP32_PANIC_SILENT_REBOOT
#define CONFIG_ESP32_PANIC_GDBSTUB
#define CONFIG_ESP32_DEBUG_OCDAWARE 1
#define CONFIG_ESP32_DEBUG_STUBS_ENABLE 1
#define CONFIG_INT_WDT 1
#define CONFIG_INT_WDT_TIMEOUT_MS 300
#define CONFIG_INT_WDT_CHECK_CPU1 1
#define CONFIG_TASK_WDT 1
#define CONFIG_TASK_WDT_PANIC 0
#define CONFIG_TASK_WDT_TIMEOUT_S 5
#define CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU0 1
#define CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU1 1
#define CONFIG_BROWNOUT_DET 1
#define CONFIG_BROWNOUT_DET_LVL_SEL_0 1
#define CONFIG_BROWNOUT_DET_LVL_SEL_1
#define CONFIG_BROWNOUT_DET_LVL_SEL_2
#define CONFIG_BROWNOUT_DET_LVL_SEL_3
#define CONFIG_BROWNOUT_DET_LVL_SEL_4
#define CONFIG_BROWNOUT_DET_LVL_SEL_5
#define CONFIG_BROWNOUT_DET_LVL_SEL_6
#define CONFIG_BROWNOUT_DET_LVL_SEL_7
#define CONFIG_BROWNOUT_DET_LVL 0
#define CONFIG_ESP32_TIME_SYSCALL_USE_RTC_FRC1 1
#define CONFIG_ESP32_TIME_SYSCALL_USE_RTC
#define CONFIG_ESP32_TIME_SYSCALL_USE_FRC1
#define CONFIG_ESP32_TIME_SYSCALL_USE_NONE
#define CONFIG_ESP32_RTC_CLOCK_SOURCE_INTERNAL_RC 1
#define CONFIG_ESP32_RTC_CLOCK_SOURCE_EXTERNAL_CRYSTAL
#define CONFIG_ESP32_RTC_CLK_CAL_CYCLES 1024
#define CONFIG_ESP32_DEEP_SLEEP_WAKEUP_DELAY 2000
#define CONFIG_ESP32_XTAL_FREQ_40 1
#define CONFIG_ESP32_XTAL_FREQ_26
#define CONFIG_ESP32_XTAL_FREQ_AUTO
#define CONFIG_ESP32_XTAL_FREQ 40
#define CONFIG_DISABLE_BASIC_ROM_CONSOLE 0
#define CONFIG_ESP_TIMER_PROFILING 0
#define CONFIG_COMPATIBLE_PRE_V2_1_BOOTLOADERS
#define CONFIG_ESP_ERR_TO_NAME_LOOKUP 1




#define CONFIG_SW_COEXIST_ENABLE 1
#define CONFIG_SW_COEXIST_PREFERENCE_WIFI 0
#define CONFIG_SW_COEXIST_PREFERENCE_BT 0
#define CONFIG_SW_COEXIST_PREFERENCE_BALANCE 1
#define CONFIG_SW_COEXIST_PREFERENCE_VALUE 2
#define CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM 10
#define CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM 32
#define CONFIG_ESP32_WIFI_STATIC_TX_BUFFER
#define CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER 1
#define CONFIG_ESP32_WIFI_TX_BUFFER_TYPE 1
#define CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM 32
#define CONFIG_ESP32_WIFI_CSI_ENABLED
#define CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED 1
#define CONFIG_ESP32_WIFI_TX_BA_WIN 6
#define CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED 1
#define CONFIG_ESP32_WIFI_RX_BA_WIN 6
#define CONFIG_ESP32_WIFI_NVS_ENABLED 1
#define CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_0 1
#define CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_1




#define CONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE 1
#define CONFIG_ESP32_PHY_INIT_DATA_IN_PARTITION
#define CONFIG_ESP32_PHY_MAX_WIFI_TX_POWER 20
#define CONFIG_ESP32_PHY_MAX_TX_POWER 20




#define CONFIG_PM_ENABLE 0




#define CONFIG_ADC_CAL_EFUSE_TP_ENABLE 1
#define CONFIG_ADC_CAL_EFUSE_VREF_ENABLE 1
#define CONFIG_ADC_CAL_LUT_ENABLE 1




#define CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS 1




#define CONFIG_DMA_RX_BUF_NUM 10
#define CONFIG_DMA_TX_BUF_NUM 10
#define CONFIG_EMAC_L2_TO_L3_RX_BUF_MODE
#define CONFIG_EMAC_TASK_PRIORITY 20




#define CONFIG_FATFS_CODEPAGE_DYNAMIC 0
#define CONFIG_FATFS_CODEPAGE_437 1
#define CONFIG_FATFS_CODEPAGE_720
#define CONFIG_FATFS_CODEPAGE_737
#define CONFIG_FATFS_CODEPAGE_771
#define CONFIG_FATFS_CODEPAGE_775
#define CONFIG_FATFS_CODEPAGE_850
#define CONFIG_FATFS_CODEPAGE_852
#define CONFIG_FATFS_CODEPAGE_855
#define CONFIG_FATFS_CODEPAGE_857
#define CONFIG_FATFS_CODEPAGE_860
#define CONFIG_FATFS_CODEPAGE_861
#define CONFIG_FATFS_CODEPAGE_862
#define CONFIG_FATFS_CODEPAGE_863
#define CONFIG_FATFS_CODEPAGE_864
#define CONFIG_FATFS_CODEPAGE_865
#define CONFIG_FATFS_CODEPAGE_866
#define CONFIG_FATFS_CODEPAGE_869
#define CONFIG_FATFS_CODEPAGE_932
#define CONFIG_FATFS_CODEPAGE_936
#define CONFIG_FATFS_CODEPAGE_949
#define CONFIG_FATFS_CODEPAGE_950
#define CONFIG_FATFS_CODEPAGE 437
#define CONFIG_FATFS_LFN_NONE 0
#define CONFIG_FATFS_LFN_HEAP 1
#define CONFIG_FATFS_LFN_STACK 0
#define CONFIG_FATFS_MAX_LFN 255
#define CONFIG_FATFS_API_ENCODING_ANSI_OEM 1
#define CONFIG_FATFS_API_ENCODING_UTF_16
#define CONFIG_FATFS_API_ENCODING_UTF_8
#define CONFIG_FATFS_FS_LOCK 0
#define CONFIG_FATFS_TIMEOUT_MS 10000
#define CONFIG_FATFS_PER_FILE_CACHE 1




#define CONFIG_FREERTOS_UNICORE 0
#define CONFIG_FREERTOS_CORETIMER_0 1
#define CONFIG_FREERTOS_CORETIMER_1 0
#define CONFIG_FREERTOS_HZ 100
#define CONFIG_FREERTOS_ASSERT_ON_UNTESTED_FUNCTION 1
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_NONE 0
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_PTRVAL 0
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_CANARY 1
#define CONFIG_FREERTOS_WATCHPOINT_END_OF_STACK 0
#define CONFIG_FREERTOS_INTERRUPT_BACKTRACE 1
#define CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS 1
#define CONFIG_FREERTOS_ASSERT_FAIL_ABORT 1
#define CONFIG_FREERTOS_ASSERT_FAIL_PRINT_CONTINUE 0
#define CONFIG_FREERTOS_ASSERT_DISABLE 0
#define CONFIG_FREERTOS_IDLE_TASK_STACKSIZE 1024
#define CONFIG_FREERTOS_ISR_STACKSIZE 1536
#define CONFIG_FREERTOS_LEGACY_HOOKS 0
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_SUPPORT_STATIC_ALLOCATION 1
#define CONFIG_ENABLE_STATIC_TASK_CLEAN_UP_HOOK 0
#define CONFIG_TIMER_TASK_PRIORITY 1
#define CONFIG_TIMER_TASK_STACK_DEPTH 2048
#define CONFIG_TIMER_QUEUE_LENGTH 10
#define CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE 0
#define CONFIG_FREERTOS_USE_TRACE_FACILITY 0
#define CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS 0
#define CONFIG_FREERTOS_DEBUG_INTERNALS 0




#define CONFIG_HEAP_POISONING_DISABLED 1
#define CONFIG_HEAP_POISONING_LIGHT 0
#define CONFIG_HEAP_POISONING_COMPREHENSIVE 0
#define CONFIG_HEAP_TRACING 0




#define CONFIG_LIBSODIUM_USE_MBEDTLS_SHA 1




#define CONFIG_LOG_DEFAULT_LEVEL_NONE 0
#define CONFIG_LOG_DEFAULT_LEVEL_ERROR 0
#define CONFIG_LOG_DEFAULT_LEVEL_WARN 0
#define CONFIG_LOG_DEFAULT_LEVEL_INFO 1
#define CONFIG_LOG_DEFAULT_LEVEL_DEBUG 0
#define CONFIG_LOG_DEFAULT_LEVEL_VERBOSE 0
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_LOG_COLORS 1




#define CONFIG_L2_TO_L3_COPY
#define CONFIG_LWIP_IRAM_OPTIMIZATION 0
#define CONFIG_LWIP_MAX_SOCKETS 10
#define CONFIG_USE_ONLY_LWIP_SELECT 0
#define CONFIG_LWIP_SO_REUSE 1
#define CONFIG_LWIP_SO_REUSE_RXTOALL 1
#define CONFIG_LWIP_SO_RCVBUF 0
#define CONFIG_LWIP_DHCP_MAX_NTP_SERVERS 1
#define CONFIG_LWIP_IP_FRAG 0
#define CONFIG_LWIP_IP_REASSEMBLY 0
#define CONFIG_LWIP_STATS 0
#define CONFIG_LWIP_ETHARP_TRUST_IP_MAC 1
#define CONFIG_TCPIP_RECVMBOX_SIZE 32
#define CONFIG_LWIP_DHCP_DOES_ARP_CHECK 1




#define CONFIG_LWIP_DHCPS_LEASE_UNIT 60
#define CONFIG_LWIP_DHCPS_MAX_STATION_NUM 8
#define CONFIG_LWIP_AUTOIP 0
#define CONFIG_LWIP_NETIF_LOOPBACK 1
#define CONFIG_LWIP_LOOPBACK_MAX_PBUFS 8




#define CONFIG_LWIP_MAX_ACTIVE_TCP 16
#define CONFIG_LWIP_MAX_LISTENING_TCP 16
#define CONFIG_TCP_MAXRTX 12
#define CONFIG_TCP_SYNMAXRTX 6
#define CONFIG_TCP_MSS 1436
#define CONFIG_TCP_MSL 60000
#define CONFIG_TCP_SND_BUF_DEFAULT 5744
#define CONFIG_TCP_WND_DEFAULT 5744
#define CONFIG_TCP_RECVMBOX_SIZE 6
#define CONFIG_TCP_QUEUE_OOSEQ 1
#define CONFIG_ESP_TCP_KEEP_CONNECTION_WHEN_IP_CHANGES 0
#define CONFIG_TCP_OVERSIZE_MSS 1
#define CONFIG_TCP_OVERSIZE_QUARTER_MSS 0
#define CONFIG_TCP_OVERSIZE_DISABLE 0




#define CONFIG_LWIP_MAX_UDP_PCBS 16
#define CONFIG_UDP_RECVMBOX_SIZE 6
#define CONFIG_TCPIP_TASK_STACK_SIZE 2048
#define CONFIG_PPP_SUPPORT 0




#define CONFIG_LWIP_MULTICAST_PING 0
#define CONFIG_LWIP_BROADCAST_PING 0




#define CONFIG_LWIP_MAX_RAW_PCBS 16




#define CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN 16384
#define CONFIG_MBEDTLS_DEBUG 0
#define CONFIG_MBEDTLS_HARDWARE_AES 1
#define CONFIG_MBEDTLS_HARDWARE_MPI 0
#define CONFIG_MBEDTLS_HARDWARE_SHA 0
#define CONFIG_MBEDTLS_HAVE_TIME 1
#define CONFIG_MBEDTLS_HAVE_TIME_DATE 0
#define CONFIG_MBEDTLS_TLS_SERVER_AND_CLIENT 1
#define CONFIG_MBEDTLS_TLS_SERVER_ONLY 0
#define CONFIG_MBEDTLS_TLS_CLIENT_ONLY 0
#define CONFIG_MBEDTLS_TLS_DISABLED 0
#define CONFIG_MBEDTLS_TLS_SERVER 1
#define CONFIG_MBEDTLS_TLS_CLIENT 1
#define CONFIG_MBEDTLS_TLS_ENABLED 1




#define CONFIG_MBEDTLS_PSK_MODES 0
#define CONFIG_MBEDTLS_KEY_EXCHANGE_RSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_RSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA 1
#define CONFIG_MBEDTLS_SSL_RENEGOTIATION 1
#define CONFIG_MBEDTLS_SSL_PROTO_SSL3
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1 1
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_1 1
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_2 1
#define CONFIG_MBEDTLS_SSL_PROTO_DTLS 0
#define CONFIG_MBEDTLS_SSL_ALPN 1
#define CONFIG_MBEDTLS_SSL_SESSION_TICKETS 1




#define CONFIG_MBEDTLS_AES_C 1
#define CONFIG_MBEDTLS_CAMELLIA_C 0
#define CONFIG_MBEDTLS_DES_C 0
#define CONFIG_MBEDTLS_RC4_DISABLED 1
#define CONFIG_MBEDTLS_RC4_ENABLED_NO_DEFAULT
#define CONFIG_MBEDTLS_RC4_ENABLED
#define CONFIG_MBEDTLS_BLOWFISH_C 0
#define CONFIG_MBEDTLS_XTEA_C 0
#define CONFIG_MBEDTLS_CCM_C 1
#define CONFIG_MBEDTLS_GCM_C 1
#define CONFIG_MBEDTLS_RIPEMD160_C




#define CONFIG_MBEDTLS_PEM_PARSE_C 1
#define CONFIG_MBEDTLS_PEM_WRITE_C 1
#define CONFIG_MBEDTLS_X509_CRL_PARSE_C 1
#define CONFIG_MBEDTLS_X509_CSR_PARSE_C 1
#define CONFIG_MBEDTLS_ECP_C 1
#define CONFIG_MBEDTLS_ECDH_C 1
#define CONFIG_MBEDTLS_ECDSA_C 1
#define CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED 1
#define CONFIG_MBEDTLS_ECP_NIST_OPTIM 1




#define CONFIG_OPENSSL_DEBUG 0
#define CONFIG_OPENSSL_ASSERT_DO_NOTHING 1
#define CONFIG_OPENSSL_ASSERT_EXIT 0




#define CONFIG_ESP32_PTHREAD_TASK_PRIO_DEFAULT 5
#define CONFIG_ESP32_PTHREAD_TASK_STACK_SIZE_DEFAULT 3072




#define CONFIG_SPI_FLASH_VERIFY_WRITE 1
#define CONFIG_SPI_FLASH_LOG_FAILED_WRITE 1
#define CONFIG_SPI_FLASH_WARN_SETTING_ZERO_TO_ONE 1
#define CONFIG_SPI_FLASH_ENABLE_COUNTERS 0
#define CONFIG_SPI_FLASH_ROM_DRIVER_PATCH 1
#define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_ABORTS 1
#define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_FAILS 0
#define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_ALLOWED 0




#define CONFIG_SPIFFS_MAX_PARTITIONS 3




#define CONFIG_SPIFFS_CACHE 1
#define CONFIG_SPIFFS_CACHE_WR 1
#define CONFIG_SPIFFS_CACHE_STATS 0
#define CONFIG_SPIFFS_PAGE_CHECK 1
#define CONFIG_SPIFFS_GC_MAX_RUNS 10
#define CONFIG_SPIFFS_GC_STATS 0
#define CONFIG_SPIFFS_PAGE_SIZE 256
#define CONFIG_SPIFFS_OBJ_NAME_LEN 32
#define CONFIG_SPIFFS_USE_MAGIC 1
#define CONFIG_SPIFFS_USE_MAGIC_LENGTH 1
#define CONFIG_SPIFFS_META_LENGTH 4
#define CONFIG_SPIFFS_USE_MTIME 1




#define CONFIG_SPIFFS_DBG 0
#define CONFIG_SPIFFS_API_DBG 0
#define CONFIG_SPIFFS_GC_DBG 0
#define CONFIG_SPIFFS_CACHE_DBG 0
#define CONFIG_SPIFFS_CHECK_DBG 0
#define CONFIG_SPIFFS_TEST_VISUALISATION 0




#define CONFIG_IP_LOST_TIMER_INTERVAL 120




#define CONFIG_SUPPRESS_SELECT_DEBUG_OUTPUT 1




#define CONFIG_WL_SECTOR_SIZE_512 1
#define CONFIG_WL_SECTOR_SIZE_4096
#define CONFIG_WL_SECTOR_SIZE 512
#define CONFIG_WL_SECTOR_MODE_PERF 0
#define CONFIG_WL_SECTOR_MODE_SAFE 1
#define CONFIG_WL_SECTOR_MODE 1
